apiVersion: v1
kind: Pod
metadata:
  name: rt-controller
  namespace: realtime
spec:
  serviceAccountName: default
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  nodeName: orionm1
  containers:
  - name: rt-controller-container
    image: stefanost2000/docker-repo:test
    imagePullPolicy: Always
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - SYS_NICE
        - IPC_OWNER
        - SYS_ADMIN
        - MKNOD
        - SYS_RESOURCE
    ports:
      - containerPort: 80
