apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rtresources.rtgroup.critical.com
spec:
  group: rtgroup.critical.com
  names:
    plural: rtresources
    singular: rtresource
    kind: RTResource
    shortNames:
    - rt
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              namespace:
                type: string
                description: "Namespace of the resource"
              replicaCount:
                type: integer
                description: "Number of Replicas"
              cpu:
                type: string
                description: "CPU Requirements"
              memory:
                type: string
                description: "Memory Requirements"
              criticality:
                type: integer
                description: "Criticality Level"
              image:
                type: string
                description: "Container Image"
