apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: Preempt-K8s
rules:
- apiGroups: ["rtgroup.critical.com"]
  resources: ["rtresources", "rtresources/status"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
