apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: preempt-k8s
  namespace: realtime
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: preempt-k8s
subjects:
  - kind: ServiceAccount
    name: preempt-k8s
    namespace: realtime
