apiVersion: v1
kind: Pod
metadata:
  name: preempt-k8s
  namespace: realtime
  labels:
    app: preempt-k8s
spec:
  serviceAccountName: preempt-k8s
  restartPolicy: Always
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  containers:
    - name: preempt-k8s-controller
      image: dessertunina/preempt-k8s:1.0.0
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: preempt-k8s
      resources:
        limits:
          cpu: "2"
          memory: "3Gi"
        requests:
          cpu: "2"
          memory: "2Gi"
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        allowPrivilegeEscalation: true
        privileged: true
        readOnlyRootFilesystem: false
        capabilities:
          add:
            - SYS_NICE
            - IPC_OWNER
            - SYS_ADMIN
            - MKNOD
            - SYS_RESOURCE
