apiVersion: v1
kind: Pod
metadata:
  name: Preempt-K8s
  namespace: realtime
  labels:
    app: Preempt-K8s
spec:
  serviceAccountName: Preempt-K8s
  restartPolicy: Always
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: Preempt-K8s-Controller
    image: stefanost2000/preempt-k8s:test
    imagePullPolicy: Always
    ports:
      - containerPort: 80
    envFrom:
    - configMapRef:
        name: Preempt-K8s
    resources:
      limits:
        cpu: "5"
        memory: "3Gi"
      requests:
        cpu: "4"
        memory: "2Gi"
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
      allowPrivilegeEscalation: false
      privileged: true
      readOnlyRootFilesystem: false
      capabilities:
        add:
        - SYS_NICE
        - IPC_OWNER
        - SYS_ADMIN
        - MKNOD
        - SYS_RESOURCE
