apiVersion: audit.k8s.io/v1
kind: Policy
omitStages:
  - "RequestReceived"
rules:
  - level: RequestResponse
    resources:
      - group: "rtgroup.critical.com"
        resources: ["rtresources"]
    namespaces: ["default"]

  - level: RequestResponse
    resources:
      - group: "apps"
        resources: ["deployments"]
    namespaces: ["default"]

  - level: RequestResponse
    resources:
      - group: ""
        resources: ["pods"]
    namespaces: ["default"]
  
  - level: None
